clear;clc;
figure;
hlist=uicontrol(gcf,'Style','list','Position',[200 200 100 80],...
    'String','red|blue|green|yellow|white|black|cyan|magenta',...
    'CallBack',['cbcol=[''r'',''b'',''g'',''y'',''w'',''k'',''c'',''m''];',...
    'set(gcf,''Color'',cbcol(get(hlist,''Value'')))']);
