clear;clc;
figure;
htxt=uicontrol(gcf,'Style','text','Position',[200 130 150 20],...
    'String','Color Options');
hr=uicontrol(gcf,'Style','radio','Position',[200 100 150 25],'String','Red',...
    'CallBack',['set(hr,''Value'',1);','set(hb,''Value'',0);',...
    'set(hy,''Value'',0);','set(gcf,''Color'',''r'');']);
hb=uicontrol(gcf,'Style','radio','Position',[200 75 150 25],'String','Blue',...
    'CallBack',['set(hr,''Value'',0);','set(hb,''Value'',1);',...
    'set(hy,''Value'',0);','set(gcf,''Color'',''b'');']);
hy=uicontrol(gcf,'Style','radio','Position',[200 50 150 25],'String','Yellow',...
    'CallBack',['set(hr,''Value'',0);','set(hb,''Value'',0);',...
    'set(hy,''Value'',1);','set(gcf,''Color'',''y'');']);