a=input('please input a: ');
theta=0:0.01:2*pi;
r1=a*(1-cos(theta));
r2=a*(1+cos(theta));
r3=a*(1-sin(theta));
r4=a*(1+sin(theta));
figure;
subplot(2,2,1);
polar(theta,r1);
title(['\bfr1=' int2str(a) '*(1-cos\theta)']);
subplot(2,2,2);
polar(theta,r2);
title(['\itr2=' int2str(a) '*(1+cos\theta)']);
subplot(2,2,3);
polar(theta,r3);
title(['\bf\itr3=' int2str(a) '*(1-sin\theta)']);
subplot(2,2,4);
polar(theta,r4);
title(['\bf\itr4=' int2str(a) '*(1+sin\theta)']);
